# ------------------------------------------
# DATA SOURCE PROPERTIES
# ------------------------------------------

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB}?useUnicode=yes&characterEncoding=UTF-8&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.MySQL5InnoDBDialect
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=20000


#--------------------------------------
#URL
#--------------------------------------
game.frontend.base.url=https://web-game.zeusis.org


# --------------------------------------------------------------------------------------------------------------------------------------------------------------
# AWS SES
# --------------------------------------------------------------------------------------------------------------------------------------------------------------
spring.mail.host=email-smtp.us-east-1.amazonaws.com
spring.mail.username=${SES_USERNAME}
spring.mail.password=${SES_PASSWORD}
mail.from=info@smartgm.it.com
spring.mail.port=587
spring.mail.properties.mail.smtp.ssl.trust=email-smtp.us-east-1.amazonaws.com
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug=false

